### ISSUE TITLE
unknown recipe category errors 

### ISSUE THREAD

**Issue by Syndaryl** [Tfarcenim/WoodCutterForge#1]
I'm getting a lot of unknown recipe category errors ("[11:13:49] [Render thread/WARN]: Unknown recipe category: woodcutter:woodcutter/woodcutter:stripped_dark_oak_log_from_dark_oak_log", that sort of thing)

I still see a recipe for this in game, and for a few others I spot checked, so I'm not sure what's going on... possibly the recipe unlock achievements?

I've popped my log up into a Gist:
https://gist.github.com/Syndaryl/cbba69de3a61e6d7c6e2003a9735c9dd

**Comment by Tfarcenim** [comment]
oh fun, it seems like trying to disable the logger doesn't work, time to apply some bytecode manipulation

**Comment by Syndaryl** [comment]
Actually, I'm creating a datapack for Biomes You'll Go (see #3) and it's giving me recipe type not found exceptions for all my recipes. Your Curseforge page says the recipe type is woodcutter:woodcutting but I took a butchers hook into your jar and you're using 'woodcutter:woodcutter' - you might want to update the curse page :)

**Comment by Tfarcenim** [comment]
that's odd, where do I use `woodcutter:woodcutter` for the type?
![image](https://user-images.githubusercontent.com/44327798/89554698-311dc400-d7dd-11ea-9139-f394286ecb60.png)

**Comment by Syndaryl** [comment]
![image](https://user-images.githubusercontent.com/8820565/89555767-755d9400-d7de-11ea-9a13-998562dabb9d.png)
This is from right out of the JAR "woodcutter-1.1-1.16.1.jar" from the Woodcutter Forge thingy delivered by the Twitch Launcher, so presumably from Curse.

**Comment by Syndaryl** [comment]
I'm dyslectic, so believe you me I went back and forth and back and forth to make sure I wasn't garbaging things up with my eyes :/

**Comment by Tfarcenim** [comment]
fixed in 1.2

**Comment by cech12** [comment]
To avoid log spam when a mod is not installed, you can add a condition to the recipes. 

See here:
https://github.com/cech12/CeramicBucket/blob/1.16/src/main/resources/data/botanypots/recipes/soil/lava_from_ceramic_bucket.json

**Comment by Tfarcenim** [comment]
this is logspam even with only the vanilla compat because mojang, anyways this was fixed.
