### ISSUE TITLE
woodcutter pack.mcmeta is out of date

### ISSUE THREAD

**Issue by Syndaryl** [Tfarcenim/WoodCutterForge#2]
For a 1.16.1 mod, you should be using pack format 5. I don't think this changes any of your files, but it will stop the datapack for your mod from showing up funny in Minecraft and might have other things IDK.

here's a replacement that also swaps out default text for something for your mod:

```
{
    "pack": {
        "description": "woodcutter resources",
        "pack_format": 5,
        "_comment": "Woodcutter Forge 1.16.1"
    }
}
```

**Comment by Tfarcenim** [comment]
actually it should be 6 now, will fix in a bit
